src/t3/pages_control/config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  resources :pages
  resources :authors

  root to: 'pages#index'
end

src/t3/pages_control/app/models/author.rb
class Author < ActiveRecord::Base
  has_many :pages

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true,
            format: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  def self.best_authors
    Author.joins(:pages).group(:id).select('authors.name, authors.email, authors.id, COUNT(*) as cc').order('cc ASC')
  end
end

src/t3/pages_control/app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId

  belongs_to :author

  friendly_id :title, use: [:finders]

  validates :author, presence: true, associated: true

  validates :description, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :title, presence: true
  validates :body, presence: true
end

src/t3/pages_control/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  responders :flash, :http_cache

  respond_to :html, :json
end

src/t3/pages_control/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.page

    respond_with(@authors)
  end

  def show
    respond_with(@author)
  end

  def new
    @author = Author.new

    respond_with(@author)
  end

  def edit; end

  def create
    @author = Author.new(author_params)
    @author.save

    respond_with(@author, location: authors_path)
  end

  def update
    @author.update(author_params)

    respond_with(@author, location: authors_path)
  end

  def destroy
    @author.destroy

    respond_with(@author, location: authors_path)
  end

  private

  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :email)
  end
end

src/t3/pages_control/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout 'live', only: :show
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.page

    respond_with(@pages)
  end

  def show
    respond_with(@page)
  end

  def new
    @page = Page.new

    respond_with(@page)
  end

  def edit; end

  def create
    @page = Page.new(page_params)
    @page.save

    respond_with(@page)
  end

  def update
    @page.update(page_params)

    respond_with(@page)
  end

  def destroy
    @page.destroy

    respond_with(@page)
  end

  private

  def set_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :description, :body, :author_id)
  end
end

src/t3/pages_control/app/helpers/globalization_helper.rb
module GlobalizationHelper
  def model_name(model, count = 1)
    model.model_name.human(count: count)
  end

  def model_name_pluralized(model)
    model_name(model, 2)
  end

  def model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, count: count)
  end

  alias_method :tm, :model_name
  alias_method :tmp, :model_name_pluralized
  alias_method :ta, :model_attribute
end

src/t3/pages_control/app/helpers/notice_manager_helper.rb
module NoticeManagerHelper
  def notices(timeout)
    flash.reject { |_, m| m.eql? true }.collect do |key, msg|
      content_tag :div, class: "ui compact closable message #{alert_class_finder(key)}" do
        concat content_tag(:span, msg, style: 'padding-right: 13px;')
        concat content_tag(:i, '', class: 'close icon', style: 'm')
      end
    end.join.html_safe
  end

  private

  def alert_class_finder(key)
    case key
    when 'notice'
      'success'
    when 'alert'
      'warning'
    end
  end
end

src/t3/pages_control/app/views/application/_menu.html.slim
.stackable.grid.container
  .ui.secondary.menu
    a.item(href="/authors" )
      = t('views.menu.authors')
    a.item(href="/pages" )
      = t('views.menu.pages')

src/t3/pages_control/app/views/authors/_form.html.slim
= simple_form_for(@author) do |f|

  .field
    = f.input :name

  .field
    = f.input :email, as: :email

  .row
    = f.button :submit, class: 'ui button positive'
    = link_to 'Back', authors_path, class: 'ui button'

src/t3/pages_control/app/views/authors/edit.html.slim
h1.ui.center.aligned.header = t 'views.crud.edit', name: tm(Author)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      == render 'form'

src/t3/pages_control/app/views/authors/index.html.slim
h1.ui.center.aligned.header = tmp(Author)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      table.ui.very.basic.table
        thead
          tr.center.aligned
            th = ta Author, :name
            th = ta Author, :email
            th

        tbody
          - @authors.each do |author|
            tr.center.aligned
              td = author.name
              td = author.email
              td(style="width: 20%")
                = link_to t('views.crud.edit_link'), edit_author_path(author), class: 'ui button tiny'
                = link_to t('views.crud.delete_link'), author, data: { confirm: t('views.crud.dialogs.confirm') }, method: :delete, class: 'ui button negative tiny'
        tfoot
          tr.right.aligned
            th(colspan="3")
              = paginate(@authors)

      = link_to t('views.crud.new_link', name: tm(Author)), new_author_path, class: 'ui button positive'

src/t3/pages_control/app/views/authors/new.html.slim
h1.ui.center.aligned.header = t 'views.crud.new', name: tm(Author)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      == render 'form'

src/t3/pages_control/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('views.project.name')

    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"]

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'menu'
    = yield
    = notices 6000

src/t3/pages_control/app/views/layouts/live.html.slim
doctype html
html
  head
    title
      = t('views.project.name')

    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"]

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'menu'
    = yield
    = notices 6000

src/t3/pages_control/app/views/pages/_form.html.slim
= simple_form_for(@page) do |f|

  .two.fields
    .field
      = f.input :title
    .field
      = f.association :author, collection: Author.all, input_html: { class: 'ui fluid dropdown' }

  .field
    = f.input :description, as: :text, input_html: { rows: 1 }

  .field
    label.text.required = ta(Page, :body)
    = f.input :body, as: :hidden

    pre#editor(style="height: 600px")

  .row
    = f.button :submit, class: 'ui button positive'
    = link_to 'Back', pages_path, class: 'ui button'


= javascript_include_tag 'ace/emmet'
= javascript_include_tag 'ace/ace'
= javascript_include_tag 'ace/ext-language_tools'
= javascript_include_tag 'ace/ext-emmet'
= javascript_include_tag 'ace/mode-html'
= javascript_include_tag 'ace/snippets/html'
= javascript_include_tag 'ace/worker-html'
= javascript_include_tag 'ace/theme-textmate'

javascript:
  ace.require("ace/ext/language_tools");
  var editor = ace.edit("editor");
  editor.session.setMode("ace/mode/html");
  editor.setTheme("ace/theme/textmate");

  editor.setOptions({
    enableBasicAutocompletion: true,
    enableLiveAutocompletion: true,
    enableSnippets: true,
    enableEmmet: true
  });

  editor.getSession().on('change', function (e) {
    $('#page_body').val(editor.getValue());
  });

  $(document).ready(function(){
    editor.setValue($('#page_body').val());
  });

src/t3/pages_control/app/views/pages/edit.html.slim
h1.ui.center.aligned.header = t 'views.crud.edit', name: tm(Page)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      == render 'form'

src/t3/pages_control/app/views/pages/index.html.slim
h1.ui.center.aligned.header = tmp(Page)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      table.ui.very.basic.table
        thead
          tr.center.aligned
            th = ta Page, :title
            th = ta Page, :slug
            th = ta Page, :author
            th = ta Page, :created_at
            th = ta Page, :updated_at
            th

        tbody
          - @pages.each do |page|
            tr.center.aligned
              td = page.title
              td = page.slug
              td = page.author.name
              td(style="width: 13%") = l page.created_at, format: :short
              td(style="width: 13%") = l page.updated_at, format: :short
              td(style="width: 20%")
                = link_to 'view', page, class: 'ui button black tiny'
                = link_to 'Edit', edit_page_path(page), class: 'ui button tiny'
                = link_to 'Destroy', page, data: { confirm: 'Are you sure?' }, method: :delete, class: 'ui button negative tiny'
        tfoot
          tr.right.aligned
            th(colspan="6")
              = paginate(@pages)

      = link_to  t('views.crud.f_new_link', name: tm(Page)), new_page_path, class: 'ui button positive'

src/t3/pages_control/app/views/pages/new.html.slim
h1.ui.center.aligned.header = t 'views.crud.new', name: tm(Page)

.ui.two.column.stackable.grid.container
  .one.column.row.center
    .column
      == render 'form'

src/t3/pages_control/app/views/pages/show.html.slim
= raw @page.body